= Cooperative Threading Library for Arduino =
---------------------------------------------------------------------------------------------------------
The Cooperative Threading library acts as a base for working with some tasks (threads) in parallel ..
---------------------------------------------------------------------------------------------------------
CoThreadBase.h / CoThreadBase.cpp
CoThreadSchedule.h / CoThreadSchedule.cpp
-	Implements base classes for object oriented cooperative multitasking

BlinkLed.h / BlinkLed.cpp
-	Implements a class for a blinking Digitalout

Button.h / Button.cpp
-	Implements a class for a digital input (Button).
	-	pull up
	-	OnKeyDown, OnKeyUp, OnKeyPressed, OnKeyPressedRepeating
	
CoServo.h / CoServo.cpp
-	Wraps the Servo.h nicely

DigitalOutput.h / DigitalOutput.cpp
-	Implements a class for wrapping a digital out

HBridge.h / HBridge.cpp
-	Implements a class for controlling a HBridge for DC motors

StepperA4988.h / StepperA4988.cpp
-	Implements a class for driving Stopper motor with Allegro A4988
	-	see: http://www.allegromicro.com/en/Products/Motor-Driver-And-Interface-ICs/Bipolar-Stepper-Motor-Drivers/A4988.aspx
	
Timer.h / Timer.cpp
-	Implements a class for programmable timer event

Ramps.h
-	Implements constants for a RAMPS - Board, see: http://reprap.org/wiki/RAMPS_1.4

Board.h
-	Defines a nice "#define BOARD" for tracing (logging)

Types.h
-	Implements various helper types

IntegerMath.h / IntegerMath.cpp
-	Implements various integer calculations

For more information about this library please visit me at https://www.facebook.com/martin.emch

== License ==

Copyright (c) 2016 Martin Emch All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
